name: This is a callable workflow
on: 
  workflow_call:
    inputs:
      artifactName:
        description: 'Name of the artifact'
        required: true
        type: string
        default: 'artifact-name'
    outputs:
      result:
        description: 'Result of the workflow'
        value: ${{ jobs.deploy.outputs.result }}
    # secrets:
    #   github_token:
    #     required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Download Package
        uses: actions/download-artifact@v6
        with:
          name: ${{ inputs.artifactName }}
      - name: LS ing files
        run: ls -la 
      - name: Printing From callback
        run: echo "This is called from another workflow "
      - name: Setting Result
        run: echo "result=success" >> $GITHUB_OUTPUT
        id: set-result
