name: Testing Security on GA
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Label
        run: |
          issue_title = "${{ github.event.issue.title }}"
          echo $issue_title
          if [[ "$issue_title" == *"bug"* ]]; then
          echo "Issue with Bug Found"
          elif [[ "$issue_title" == *"security"* ]]; then
          echo "Security Issue Found"
          else
          echo "Other Issue"
          fi
