name: Testing Security on GA
on:
  issues:
    types: [opened, edited, reopened]
permissions:
  issues: write
  contents: read
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue Title
        run: |
          issue_title="${{ github.event.issue.title }}"
          echo $issue_title
          if [[ "$issue_title" == *"bug"* ]]; then
          echo "Issue with Bug Found"
          elif [[ "$issue_title" == *"security"* ]]; then
          echo "Security Issue Found"
          else
          echo "Other Issue"
          fi
      
      - name: Assign Lable
        if: contains(github.event.issue.title, 'security')
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{ "labels": ["security"] }' \
          --fail