name: Context Objects

on:
  workflow_dispatch:
    inputs:
      dispatch_user:
        default: powerUser
        description: Who is running this?
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print All Contexts
        run: |
          echo "GITHUB CONTEXT"
          echo '${{ toJson(github) }}' | jq

          echo "JOB CONTEXT"
          echo '${{ toJson(job) }}' | jq

          echo "RUNNER CONTEXT"
          echo '${{ toJson(runner) }}' | jq

          echo "STRATEGY CONTEXT"
          echo '${{ toJson(strategy) }}' | jq

          echo "MATRIX CONTEXT"
          echo '${{ toJson(matrix) }}' | jq

          echo "ENV CONTEXT"
          echo '${{ toJson(env) }}' | jq

          echo "VARS CONTEXT"
          echo '${{ toJson(vars) }}' | jq
